### PR TITLE
update project template, fix codecov

### PR DESCRIPTION
**Pull request by hangqianjun**
Updating the project template
Adding codecov token to secret

### CODE REVIEW

**Comment by hangqianjun** [comment]
@sschmidt23 A bunch of things changed when I updated the project template. Probably worth having a look if any of these is unwanted.

**Comment by hangqianjun** [comment]
...also didn't find the "Settings" tab to add the token. So codecov token is not yet added for this repo!!

**Comment by sschmidt23** [comment]
Ok, it looks like the copier stuff either wasn't set up or wasn't updated in a long time, so a lot of changes were brought in, I'll take a look and try to figure out why the linter step can't install mpi4py properly after the update.

**Review by sschmidt23 — APPROVED** [review]
Looks good and codecov is working again, approving and will merge

**Pull request merged**
